### PR TITLE
Homework Submission

### PR DESCRIPTION
**Pull request by pacalabre**
I was pretty frustrated that I could not get the classes to stick in the JS dom manipulation.

### CODE REVIEW

**Comment by pacalabre** [comment]
Updated with output box changing color based on temp.

**Comment by geluso** [comment]
Nice work styling the page and changing the background color. Your page only converts from Fahrenheit to Celcius. You'd need to add another button, or something like that, in order to have your page support F to C and C to F.

You're adding the className property to a list, not to the actual element. Be careful when selecting elements. This line returns an array of all elements matching your selector.

```
var changeToRed = document.getElementsByTagName("section");
changeToRed.className = "hot";
```

If you choose the first element of the list at index zero ```[0]``` then your code will work.

```
var changeToRed = document.getElementsByTagName("section")[0];
changeToRed.className = "hot";
```

**Comment by geluso** [comment]
This line works because the ```document.getElementById``` function always returns only one item because IDs are ever only on one thing. It doesn't return a list of elements like the other selector functions.

```
var changeToRed = document.getElementById("area");
```

**Comment by geluso** [comment]
Finally, always use the ```className``` property to set class names for an element. The ```classList``` property is a read-only property and the DOM doesn't allow you to change anything that way.

```
changeToRed.className = "hot"; // great!
changeToRed.classList.add('hot'); // won't work
```

Here's some docs on MDN:

```
The Element.classList is a read-only property which returns live DOMTokenList collection of the class attributes of the element.
```
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Pull request closed without merging**
